# Generated by Django 4.1.4 on 2023-02-06 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='providers',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='productsimg'),
        ),
    ]
